force-app/main/default/objects/Contact/fields/DateofJoining__c.field-meta.xml
<CustomField>
    <fullName>DateofJoining__c</fullName>
    <label>Date of Joining</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EmployeeNumber__c.field-meta.xml
<CustomField>
    <fullName>EmployeeNumber__c</fullName>
    <label>Employee Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EmployeeRole__c.field-meta.xml
<CustomField>
    <fullName>EmployeeRole__c</fullName>
    <label>Employee Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ProjectManager__c.field-meta.xml
<CustomField>
    <fullName>ProjectManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ReportingManager__c.field-meta.xml
<CustomField>
    <fullName>ReportingManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Reporting Manager)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkSpace__c/WorkSpace__c.object-meta.xml
<CustomObject>
    <label>WorkSpace</label>
    <nameField>
        <displayFormat>WS-{0000}</displayFormat>
        <label>WorkSpace Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WorkSpace</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkSpace__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>WorkSpace</relationshipLabel>
    <relationshipName>WorkSpace</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkSpace__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Workspace_Info__c/Workspace_Info__c.object-meta.xml
<CustomObject>
    <label>Workspace Info</label>
    <nameField>
        <label>Workspace Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workspace Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Workspace_Info__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workspace_Info__c/fields/Shape__c.field-meta.xml
<CustomField>
    <fullName>Shape__c</fullName>
    <label>Shape</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Square</fullName>
            </value>
            <value>
                <fullName>Rectangle</fullName>
            </value>
            <value>
                <fullName>Circle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Workspace_Info__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workspace_Info__c/fields/WorkSpace__c.field-meta.xml
<CustomField>
    <fullName>WorkSpace__c</fullName>
    <label>WorkSpace</label>
    <referenceTo>WorkSpace__c</referenceTo>
    <relationshipLabel>Workspace Info</relationshipLabel>
    <relationshipName>WorkspaceInfo</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Workspace_Info__c/fields/Workspace_No__c.field-meta.xml
<CustomField>
    <fullName>Workspace_No__c</fullName>
    <label>Workspace No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Workspace_Info__c/fields/WorkspaceAvailability__c.field-meta.xml
<CustomField>
    <fullName>WorkspaceAvailability__c</fullName>
    <label>Workspace Availability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Workspace_Info__c/fields/WorkspaceType__c.field-meta.xml
<CustomField>
    <fullName>WorkspaceType__c</fullName>
    <label>Workspace Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cabin</fullName>
            </value>
            <value>
                <fullName>Meeting Room</fullName>
            </value>
            <value>
                <fullName>Desk</fullName>
            </value>
            <value>
                <fullName>Conference Room</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Workspace_Info__c/fields/XCoordinate__c.field-meta.xml
<CustomField>
    <fullName>XCoordinate__c</fullName>
    <label>X Coordinate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workspace_Info__c/fields/YCoordinate__c.field-meta.xml
<CustomField>
    <fullName>YCoordinate__c</fullName>
    <label>Y Coordinate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkspaceBooking__c/WorkspaceBooking__c.object-meta.xml
<CustomObject>
    <label>Workspace Booking</label>
    <nameField>
        <displayFormat>WB-{0000}</displayFormat>
        <label>Workspace Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workspace Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkspaceBooking__c/fields/BookedforDate__c.field-meta.xml
<CustomField>
    <fullName>BookedforDate__c</fullName>
    <label>Booked for Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkspaceBooking__c/fields/BookingStatus__c.field-meta.xml
<CustomField>
    <fullName>BookingStatus__c</fullName>
    <label>Booking Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkspaceBooking__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Workspace Bookings</relationshipLabel>
    <relationshipName>Workspace_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkspaceBooking__c/fields/WorkspaceInfo__c.field-meta.xml
<CustomField>
    <fullName>WorkspaceInfo__c</fullName>
    <label>Workspace Info</label>
    <referenceTo>Workspace_Info__c</referenceTo>
    <relationshipLabel>Workspace Bookings</relationshipLabel>
    <relationshipName>Workspace_Bookings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkspaceBooking__c/fields/WorkspaceType__c.field-meta.xml
<CustomField>
    <fullName>WorkspaceType__c</fullName>
    <formula>TEXT(WorkspaceInfo__r.WorkspaceType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Workspace Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SeatBookingHelper.cls
public without sharing class SeatBookingHelper {
    @AuraEnabled
    public static Contact getContact(String empId){
        try{
            return [SELECT Id, Name, MobilePhone, ReportsToId, Email, Title, Department, AssistantName, LeadSource, 
                    Birthdate, PhotoUrl, EmployeeNumber__c, EmployeeRole__c, DateofJoining__c, ProjectManager__c, 
                    ReportingManager__c FROM Contact WHERE Id=:empId LIMIT 1];
        }catch(exception ex){
            return null;
        }
    }
	@AuraEnabled
    public static EmpDeskInfo showAvailableDesks(String empId, Date bookedDate,String buildingId,String floorId){
        try{
            EmpDeskInfo empData = new EmpDeskInfo();
            Integer bookCount = 0;
            String employeeRole = [SELECT Id, EmployeeRole__c FROM Contact WHERE Id=:empId LIMIT 1].EmployeeRole__c;
            List<DeskInfo> desks = new List<DeskInfo>();
            Set<Id> winfoIds = new Set<Id>();
            Map<Id, WorkspaceBooking__c> mapData = new Map<Id, WorkspaceBooking__c>();
            List<Workspace_Info__c> deskSpaceRecs = [SELECT Id, Name, WorkSpace__c, Workspace_No__c,WorkspaceAvailability__c, 
                                                     WorkspaceType__c,XCoordinate__c, YCoordinate__c,  Height__c, Width__c,
                                                     Shape__c FROM Workspace_Info__c WHERE WorkSpace__r.Building__c=:buildingId
                                                     AND WorkSpace__c=:floorId];
            for(Workspace_Info__c rec : deskSpaceRecs){
                winfoIds.add(rec.Id);
            }
            List<WorkspaceBooking__c> bookings = [SELECT Id, Name,Employee__r.Name, Employee__r.EmployeeNumber__c, 
                                                 Employee__r.EmployeeRole__c,Employee__r.ProjectManager__c, 
                                                 Employee__r.ReportsToId, WorkspaceInfo__c, BookingStatus__c,
            									 BookedforDate__c,StartTime__c,EndTime__c FROM WorkspaceBooking__c WHERE 
                                                 BookedforDate__c=:bookedDate AND WorkspaceInfo__c IN : winfoIds];
            for(WorkspaceBooking__c rec : bookings){
                mapData.put(rec.WorkspaceInfo__c, rec);
            }
            for(Workspace_Info__c rec : deskSpaceRecs){
                DeskInfo deskRec = new DeskInfo();
                deskRec.employeeName = '';
                deskRec.employeeId = '';
                deskRec.employeeRole = '';
                deskRec.seatNo = rec.Workspace_No__c;
                deskRec.isDeskBooked = false;
                deskRec.selected = false;
                deskRec.workspaceId= rec.Id;
                deskRec.isDelete = false;
                deskRec.workSpaceType = rec.WorkspaceType__c;
                deskRec.disableDesk = false; 
                String bookedStatus = 'Available';
                if(mapData.containsKey(rec.Id)){
                    deskRec.bookedStatus = mapData.get(rec.Id).BookingStatus__c;
                    bookedStatus = mapData.get(rec.Id).BookingStatus__c;
                    deskRec.employeeName = mapData.get(rec.Id).Employee__r?.Name;
                	deskRec.employeeId = mapData.get(rec.Id).Employee__c;
                	deskRec.employeeRole = mapData.get(rec.Id).Employee__r?.EmployeeRole__c;
                    //deskRec.isDeskBooked = bookedStatus == 'Booked' || bookedStatus == 'Reserved' ? true : false;
                    deskRec.bookedCss = bookedStatus == 'Booked' || bookedStatus == 'Reserved' ? 'success' : 'default';
                	deskRec.startTime = String.valueOf(mapData.get(rec.Id).StartTime__c);
                    deskRec.endTime = String.valueOf(mapData.get(rec.Id).EndTime__c);
                    deskRec.isDelete = mapData.get(rec.Id).BookedforDate__c < system.Today() ? false : true;
                    deskRec.bookingRecId = mapData.get(rec.Id).Id;
                    if(mapData.get(rec.Id).Employee__c==empId && bookedStatus == 'Booked'){
                       bookCount =bookCount+1;
                    }
                    if(employeeRole=='Admin' && (bookedStatus == 'Booked' || bookedStatus == 'Reserved' || 
                                                bookedStatus == 'Pending' || bookedStatus == 'Rejected')){
                        deskRec.isDeskBooked = true;
                    }
                    else if((employeeRole=='Employee' || employeeRole=='Manager') && 
                            (bookedStatus == 'Booked' || bookedStatus == 'Reserved' || bookedStatus == 'Pending'
                             || bookedStatus == 'Rejected')){
                        deskRec.isDeskBooked = true;
                    }
                    system.debug(bookCount);
                }
                if((employeeRole=='Admin') || (employeeRole=='Employee') && rec.WorkspaceType__c != 'Desk'){
                   deskRec.disableDesk = true; 
                }
                String booked = mapData.containsKey(rec.Id) ? 'white' : 'black';
                String style = 'left:'+String.valueOf(rec.XCoordinate__c)+'px;top:'+String.valueOf(rec.YCoordinate__c)
                        			+'px;border:2px solid '+booked+';width:'+String.valueOf(rec.Width__c)+
                        			'px;height:'+String.valueOf(rec.Height__c)+'px;';
                style = rec.Shape__c == 'Circle' ? style+'border-radius:50%;' : style;
                deskRec.style = (bookedStatus == 'Booked' || bookedStatus == 'Reserved') && deskRec.employeeId==empId  ? style+'background-color: green;' 
                    			: bookedStatus == 'Booked' || bookedStatus == 'Reserved' ? style+'background-color: #FC6666;' 
                    			: bookedStatus == 'Available' ? style+'background-color: #DAD3C9;' 
                                : bookedStatus == 'Pending' ? style+'background-color: #FFCD99;' 
                				: bookedStatus == 'Rejected' ? style+'background-color: #ffb307;' : style;//opacity: .4;
                deskRec.bookedDate = system.today();
                desks.add(deskRec);
            }
            empData.deskInfo = new List<DeskInfo>();
            empData.deskInfo = desks;
            empData.bookCount = bookCount;
            empData.empId = empId;
            empData.empRole = employeeRole;
        	return empData;
        }catch(exception ex){
            return null;
        }
    }
    @AuraEnabled
    public static List<Map<String,String>> getBuildingAndFloors(){
        try{
            List<Map<String,String>> options =new List<Map<String,String>>();
            List<Id> ids = new List<Id>();
            for(WorkSpace__c ws : [SELECT Id,Building__r.Name,Building__c FROM WorkSpace__c WHERE Building__c!=null]){
                if(!ids.contains(ws.Building__c)){
                    Map<String,String> option = new Map<String,String>{'label'=>ws.Building__r.Name,'value'=>ws.Building__c};                           
                    options.add(option);
                    ids.add(ws.Building__c);
                }
            }
            return options;
        }catch(exception ex){
            return null;
        }
    }
    @AuraEnabled
    public static List<Map<String,String>> getBuildingFloors(String buildingId){
        try{
            List<Map<String,String>> options =new List<Map<String,String>>();
            for(WorkSpace__c ws : [SELECT Id,Floor__c FROM WorkSpace__c WHERE Building__c=:buildingId]){
                Map<String,String> option = new Map<String,String>{'label'=>ws.Floor__c,'value'=>ws.Id};                           
                options.add(option); 
            }
            return options;
        }catch(exception ex){
            return null;
        }
    }
    @AuraEnabled
    public static String deleteSObjectRecord(List<Id> ids){
        try{
            List<WorkspaceBooking__c> recordsToDelete = new List<WorkspaceBooking__c>();
            for(Id recId : ids){
                WorkspaceBooking__c rec = new WorkspaceBooking__c(Id=recId);
                recordsToDelete.add(rec);
            }
            delete recordsToDelete;
            return 'success';
        }catch(exception ex){
            return ex.getMessage();
        }
    }
    @AuraEnabled
    public static String saveWorkspaceRecords(List<WorkspaceBooking__c> records){
        try{
            insert records;
            return 'success';
        }catch(exception ex){
            return ex.getMessage();
        }
    }
    @AuraEnabled
    public static String updateWorkspaceRecords(List<WorkspaceBooking__c> records){
        try{
            update records;
            return 'success';
        }catch(exception ex){
            return ex.getMessage();
        }
    }
    public class EmpDeskInfo{
        @AuraEnabled
        public String empId {set;get;}
        @AuraEnabled
        public String empRole {set;get;}
        @AuraEnabled
        public List<DeskInfo> deskInfo {set;get;}
        @AuraEnabled
        public Integer bookCount {set;get;}
    }
    public class DeskInfo{
        @AuraEnabled
        public String employeeName {set;get;}
        @AuraEnabled
        public String employeeId {set;get;}
        @AuraEnabled
        public String employeeRole {set;get;}
        @AuraEnabled
        public String workspaceId {set;get;}
        @AuraEnabled
        public String seatNo {set;get;}
        @AuraEnabled
        public Boolean isDeskBooked {set;get;}
        @AuraEnabled
        public Date bookedDate {set;get;}
        @AuraEnabled
        public Boolean disableDesk {set;get;}
        @AuraEnabled
        public String style {set;get;}
        @AuraEnabled
        public String startTime {set;get;}
        @AuraEnabled
        public String endTime {set;get;}
        @AuraEnabled
        public Boolean selected {set;get;}
        @AuraEnabled
        public Boolean isDelete {set;get;}
        @AuraEnabled
        public String workSpaceType {set;get;}
        @AuraEnabled
        public String bookingRecId {set;get;}
        @AuraEnabled
        public String bookedCss {set;get;}
        @AuraEnabled
        public String bookedStatus {set;get;}
        
    }
}